// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen3_screen_init(void)
{
ui_Screen3 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ButtonBack1 = lv_btn_create(ui_Screen3);
lv_obj_set_width( ui_ButtonBack1, 55);
lv_obj_set_height( ui_ButtonBack1, 35);
lv_obj_set_x( ui_ButtonBack1, 210 );
lv_obj_set_y( ui_ButtonBack1, 115 );
lv_obj_set_align( ui_ButtonBack1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonBack1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonBack1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonBack1, lv_color_hex(0x00FF30), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonBack1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ForwardButton = lv_btn_create(ui_Screen3);
lv_obj_set_width( ui_ForwardButton, 50);
lv_obj_set_height( ui_ForwardButton, 50);
lv_obj_set_x( ui_ForwardButton, 90 );
lv_obj_set_y( ui_ForwardButton, -70 );
lv_obj_set_align( ui_ForwardButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ForwardButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ForwardButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_ForwardButton, &ui_img_483416384, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_LeftButton = lv_btn_create(ui_Screen3);
lv_obj_set_width( ui_LeftButton, 50);
lv_obj_set_height( ui_LeftButton, 50);
lv_obj_set_x( ui_LeftButton, 30 );
lv_obj_set_y( ui_LeftButton, -10 );
lv_obj_set_align( ui_LeftButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_LeftButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_LeftButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_LeftButton, &ui_img_325661808, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_RightButton = lv_btn_create(ui_Screen3);
lv_obj_set_width( ui_RightButton, 50);
lv_obj_set_height( ui_RightButton, 50);
lv_obj_set_x( ui_RightButton, 150 );
lv_obj_set_y( ui_RightButton, -10 );
lv_obj_set_align( ui_RightButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RightButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RightButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_RightButton, &ui_img_1134473259, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_BackwardButton = lv_btn_create(ui_Screen3);
lv_obj_set_width( ui_BackwardButton, 50);
lv_obj_set_height( ui_BackwardButton, 50);
lv_obj_set_x( ui_BackwardButton, 90 );
lv_obj_set_y( ui_BackwardButton, 50 );
lv_obj_set_align( ui_BackwardButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BackwardButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BackwardButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_BackwardButton, &ui_img_798946583, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Velocity = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_Velocity, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Velocity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Velocity, -126 );
lv_obj_set_y( ui_Velocity, 46 );
lv_obj_set_align( ui_Velocity, LV_ALIGN_CENTER );
lv_label_set_text(ui_Velocity,"");

ui_Speedometer = lv_img_create(ui_Screen3);
lv_img_set_src(ui_Speedometer, &ui_img_582018047);
lv_obj_set_width( ui_Speedometer, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Speedometer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Speedometer, -123 );
lv_obj_set_y( ui_Speedometer, -23 );
lv_obj_set_align( ui_Speedometer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Speedometer, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Speedometer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Speedometer,400);

lv_obj_add_event_cb(ui_ButtonBack1, ui_event_ButtonBack1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ForwardButton, ui_event_ForwardButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_LeftButton, ui_event_LeftButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_RightButton, ui_event_RightButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BackwardButton, ui_event_BackwardButton, LV_EVENT_ALL, NULL);

}
