// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1( lv_event_t * e);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Homescreen;
void ui_event_TouchScreen( lv_event_t * e);
lv_obj_t *ui_TouchScreen;
void ui_event_CreditScreen( lv_event_t * e);
lv_obj_t *ui_CreditScreen;
void ui_event_ControlScreen( lv_event_t * e);
lv_obj_t *ui_ControlScreen;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t *ui_Screen2;
void ui_event_ButtonBack( lv_event_t * e);
lv_obj_t *ui_ButtonBack;
lv_obj_t *ui_Car;
lv_obj_t *ui_Finger1;
lv_obj_t *ui_Finger2;
lv_obj_t *ui_Finger3;
lv_obj_t *ui_Finger4;


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t *ui_Screen3;
void ui_event_ButtonBack1( lv_event_t * e);
lv_obj_t *ui_ButtonBack1;
void ui_event_ForwardButton( lv_event_t * e);
lv_obj_t *ui_ForwardButton;
void ui_event_LeftButton( lv_event_t * e);
lv_obj_t *ui_LeftButton;
void ui_event_RightButton( lv_event_t * e);
lv_obj_t *ui_RightButton;
void ui_event_BackwardButton( lv_event_t * e);
lv_obj_t *ui_BackwardButton;
lv_obj_t *ui_Velocity;
lv_obj_t *ui_Speedometer;
void ui_event_StopButton( lv_event_t * e);
lv_obj_t *ui_StopButton;


// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
lv_obj_t *ui_Screen5;
void ui_event_ButtonBack2( lv_event_t * e);
lv_obj_t *ui_ButtonBack2;
lv_obj_t *ui_Credit;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_1181843090[1] = {&ui_img_798946583};
const lv_img_dsc_t *ui_imgset_598973145[1] = {&ui_img_2016198774};
const lv_img_dsc_t *ui_imgset_353751797[1] = {&ui_img_325661808};
const lv_img_dsc_t *ui_imgset_37493096[1] = {&ui_img_1016388178};
const lv_img_dsc_t *ui_imgset_1197924266[1] = {&ui_img_1134473259};
const lv_img_dsc_t *ui_imgset_444053641[1] = {&ui_img_582018047};
const lv_img_dsc_t *ui_imgset_1742190239[1] = {&ui_img_483416384};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_delete( &ui_Screen1);
}
}
void ui_event_TouchScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
      _ui_screen_delete( &ui_Screen1);
}
}
void ui_event_CreditScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen5_screen_init);
      _ui_screen_delete( &ui_Screen1);
}
}
void ui_event_ControlScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
      _ui_screen_delete( &ui_Screen1);
}
}
void ui_event_ButtonBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
      _ui_screen_delete( &ui_Screen2);
}
}
void ui_event_ButtonBack1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
      _ui_screen_delete( &ui_Screen3);
}
}
void ui_event_ForwardButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      moveForward( e );
}
}
void ui_event_LeftButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      moveLeft( e );
}
}
void ui_event_RightButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      moveRight( e );
}
}
void ui_event_BackwardButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      moveBackward( e );
}
}
void ui_event_StopButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      stopMotor( e );
}
}
void ui_event_ButtonBack2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
      _ui_screen_delete( &ui_Screen5);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui_Screen2_screen_init();
ui_Screen3_screen_init();
ui_Screen5_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
