// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1( lv_event_t * e);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Homescreen;
void ui_event_TouchScreen( lv_event_t * e);
extern lv_obj_t *ui_TouchScreen;
void ui_event_CreditScreen( lv_event_t * e);
extern lv_obj_t *ui_CreditScreen;
void ui_event_ControlScreen( lv_event_t * e);
extern lv_obj_t *ui_ControlScreen;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t *ui_Screen2;
void ui_event_ButtonBack( lv_event_t * e);
extern lv_obj_t *ui_ButtonBack;
extern lv_obj_t *ui_Car;
extern lv_obj_t *ui_Finger1;
extern lv_obj_t *ui_Finger2;
extern lv_obj_t *ui_Finger3;
extern lv_obj_t *ui_Finger4;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t *ui_Screen3;
void ui_event_ButtonBack1( lv_event_t * e);
extern lv_obj_t *ui_ButtonBack1;
void ui_event_ForwardButton( lv_event_t * e);
extern lv_obj_t *ui_ForwardButton;
void ui_event_LeftButton( lv_event_t * e);
extern lv_obj_t *ui_LeftButton;
void ui_event_RightButton( lv_event_t * e);
extern lv_obj_t *ui_RightButton;
void ui_event_BackwardButton( lv_event_t * e);
extern lv_obj_t *ui_BackwardButton;
extern lv_obj_t *ui_Velocity;
extern lv_obj_t *ui_Speedometer;
void ui_event_StopButton( lv_event_t * e);
extern lv_obj_t *ui_StopButton;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t *ui_Screen5;
void ui_event_ButtonBack2( lv_event_t * e);
extern lv_obj_t *ui_ButtonBack2;
extern lv_obj_t *ui_Credit;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_1016388178);   // assets\icons8-race-car-48.png
LV_IMG_DECLARE( ui_img_2016198774);   // assets\icons8-finger-up-50.png
LV_IMG_DECLARE( ui_img_483416384);   // assets\icons8-up-arrow-30.png
LV_IMG_DECLARE( ui_img_325661808);   // assets\icons8-left-arrow-30.png
LV_IMG_DECLARE( ui_img_1134473259);   // assets\icons8-right-arrow-30.png
LV_IMG_DECLARE( ui_img_798946583);   // assets\icons8-down-arrow-30.png
LV_IMG_DECLARE( ui_img_582018047);   // assets\icons8-speedometer-64.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
