// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1( lv_event_t * e);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Label4;
void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
void ui_event_Button3( lv_event_t * e);
extern lv_obj_t *ui_Button3;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t *ui_Screen2;
void ui_event_Button5( lv_event_t * e);
extern lv_obj_t *ui_Button5;
void ui_event_Checkbox1( lv_event_t * e);
extern lv_obj_t *ui_Checkbox1;
void ui_event_Slider1( lv_event_t * e);
extern lv_obj_t *ui_Slider1;
void ui_event_Slider2( lv_event_t * e);
extern lv_obj_t *ui_Slider2;
void ui_event_Slider3( lv_event_t * e);
extern lv_obj_t *ui_Slider3;
void ui_event_Slider4( lv_event_t * e);
extern lv_obj_t *ui_Slider4;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Label9;
void ui_event_Switch1( lv_event_t * e);
extern lv_obj_t *ui_Switch1;
void ui_event_Switch2( lv_event_t * e);
extern lv_obj_t *ui_Switch2;
void ui_event_Switch3( lv_event_t * e);
extern lv_obj_t *ui_Switch3;
void ui_event_Switch4( lv_event_t * e);
extern lv_obj_t *ui_Switch4;
extern lv_obj_t *ui_Button9;
extern lv_obj_t *ui_Button10;
extern lv_obj_t *ui_Button11;
extern lv_obj_t *ui_Button12;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_Label15;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t *ui_Screen3;
void ui_event_Button6( lv_event_t * e);
extern lv_obj_t *ui_Button6;
void ui_event_Arc2( lv_event_t * e);
extern lv_obj_t *ui_Arc2;
void ui_event_Button13( lv_event_t * e);
extern lv_obj_t *ui_Button13;
void ui_event_Button14( lv_event_t * e);
extern lv_obj_t *ui_Button14;
void ui_event_Button15( lv_event_t * e);
extern lv_obj_t *ui_Button15;
void ui_event_Button16( lv_event_t * e);
extern lv_obj_t *ui_Button16;
extern lv_obj_t *ui_Label10;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t *ui_Screen5;
void ui_event_Button8( lv_event_t * e);
extern lv_obj_t *ui_Button8;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_472371_png);   // assets\472371.png
LV_IMG_DECLARE( ui_img_568182_png);   // assets\568182.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
