// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1( lv_event_t * e);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Label4;
void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
void ui_event_Button3( lv_event_t * e);
extern lv_obj_t *ui_Button3;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t *ui_Screen2;
void ui_event_Button4( lv_event_t * e);
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_Image6;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t *ui_Screen3;
void ui_event_Button6( lv_event_t * e);
extern lv_obj_t *ui_Button6;
void ui_event_Arc2( lv_event_t * e);
extern lv_obj_t *ui_Arc2;
void ui_event_Button13( lv_event_t * e);
extern lv_obj_t *ui_Button13;
void ui_event_Button14( lv_event_t * e);
extern lv_obj_t *ui_Button14;
void ui_event_Button15( lv_event_t * e);
extern lv_obj_t *ui_Button15;
void ui_event_Button16( lv_event_t * e);
extern lv_obj_t *ui_Button16;
extern lv_obj_t *ui_Label10;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t *ui_Screen5;
void ui_event_Button8( lv_event_t * e);
extern lv_obj_t *ui_Button8;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_1016388178);   // assets\icons8-race-car-48.png
LV_IMG_DECLARE( ui_img_2016198774);   // assets\icons8-finger-up-50.png
LV_IMG_DECLARE( ui_img_472371_png);   // assets\472371.png
LV_IMG_DECLARE( ui_img_568182_png);   // assets\568182.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
