// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void moveForward(lv_event_t * e)
{
	// Your code here
  //Serial.println("Move forward");
}

void moveLeft(lv_event_t * e)
{
	// Your code here
 //Serial.println("Move left");
}

void moveRight(lv_event_t * e)
{
	// Your code here
 //Serial.println("Move right");
}

void moveBackward(lv_event_t * e)
{
	// Your code here
 //Serial.println("Move backward");
}
