// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

int directionButton = 0;
void moveForward(lv_event_t * e)
{
	// Your code here
  directionButton = 1;
}

void moveLeft(lv_event_t * e)
{
	// Your code here
 //Serial.println("Move left");
  directionButton = 2;
}

void moveRight(lv_event_t * e)
{
	// Your code here
  directionButton = 3;
}

void moveBackward(lv_event_t * e)
{
	// Your code here
  directionButton = 4;
}
