// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ButtonBack = lv_btn_create(ui_Screen2);
lv_obj_set_width( ui_ButtonBack, 55);
lv_obj_set_height( ui_ButtonBack, 35);
lv_obj_set_x( ui_ButtonBack, 210 );
lv_obj_set_y( ui_ButtonBack, 115 );
lv_obj_set_align( ui_ButtonBack, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonBack, lv_color_hex(0xFE0303), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Car = lv_img_create(ui_Screen2);
lv_img_set_src(ui_Car, &ui_img_1016388178);
lv_obj_set_width( ui_Car, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Car, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Car, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Car, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Car, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Car,-900);
lv_img_set_zoom(ui_Car,500);

ui_Finger1 = lv_img_create(ui_Screen2);
lv_img_set_src(ui_Finger1, &ui_img_2016198774);
lv_obj_set_width( ui_Finger1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Finger1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Finger1, -92 );
lv_obj_set_y( ui_Finger1, -75 );
lv_obj_set_align( ui_Finger1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Finger1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Finger1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Finger1,-6000);

ui_Finger2 = lv_img_create(ui_Screen2);
lv_img_set_src(ui_Finger2, &ui_img_2016198774);
lv_obj_set_width( ui_Finger2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Finger2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Finger2, 92 );
lv_obj_set_y( ui_Finger2, -75 );
lv_obj_set_align( ui_Finger2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Finger2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Finger2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Finger2,6000);

ui_Finger3 = lv_img_create(ui_Screen2);
lv_img_set_src(ui_Finger3, &ui_img_2016198774);
lv_obj_set_width( ui_Finger3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Finger3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Finger3, -92 );
lv_obj_set_y( ui_Finger3, 92 );
lv_obj_set_align( ui_Finger3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Finger3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Finger3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Finger3,450);

ui_Finger4 = lv_img_create(ui_Screen2);
lv_img_set_src(ui_Finger4, &ui_img_2016198774);
lv_obj_set_width( ui_Finger4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Finger4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Finger4, 92 );
lv_obj_set_y( ui_Finger4, 92 );
lv_obj_set_align( ui_Finger4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Finger4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Finger4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Finger4,-450);

lv_obj_add_event_cb(ui_ButtonBack, ui_event_ButtonBack, LV_EVENT_ALL, NULL);

}
