// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen3_screen_init(void)
{
ui_Screen3 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button6 = lv_btn_create(ui_Screen3);
lv_obj_set_width( ui_Button6, 55);
lv_obj_set_height( ui_Button6, 35);
lv_obj_set_x( ui_Button6, 210 );
lv_obj_set_y( ui_Button6, 115 );
lv_obj_set_align( ui_Button6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x00FF30), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Arc2 = lv_arc_create(ui_Screen3);
lv_obj_set_width( ui_Arc2, 150);
lv_obj_set_height( ui_Arc2, 150);
lv_obj_set_x( ui_Arc2, -123 );
lv_obj_set_y( ui_Arc2, -6 );
lv_obj_set_align( ui_Arc2, LV_ALIGN_CENTER );


ui_Button13 = lv_btn_create(ui_Screen3);
lv_obj_set_width( ui_Button13, 50);
lv_obj_set_height( ui_Button13, 50);
lv_obj_set_x( ui_Button13, 90 );
lv_obj_set_y( ui_Button13, -70 );
lv_obj_set_align( ui_Button13, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button14 = lv_btn_create(ui_Screen3);
lv_obj_set_width( ui_Button14, 50);
lv_obj_set_height( ui_Button14, 50);
lv_obj_set_x( ui_Button14, 30 );
lv_obj_set_y( ui_Button14, -10 );
lv_obj_set_align( ui_Button14, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button14, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button15 = lv_btn_create(ui_Screen3);
lv_obj_set_width( ui_Button15, 50);
lv_obj_set_height( ui_Button15, 50);
lv_obj_set_x( ui_Button15, 150 );
lv_obj_set_y( ui_Button15, -10 );
lv_obj_set_align( ui_Button15, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button15, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button16 = lv_btn_create(ui_Screen3);
lv_obj_set_width( ui_Button16, 50);
lv_obj_set_height( ui_Button16, 50);
lv_obj_set_x( ui_Button16, 90 );
lv_obj_set_y( ui_Button16, 50 );
lv_obj_set_align( ui_Button16, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button16, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button16, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label10 = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, -126 );
lv_obj_set_y( ui_Label10, 46 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"");

lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Arc2, ui_event_Arc2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button13, ui_event_Button13, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button14, ui_event_Button14, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button15, ui_event_Button15, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button16, ui_event_Button16, LV_EVENT_ALL, NULL);

}
