// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen5_screen_init(void)
{
ui_Screen5 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ButtonBack2 = lv_btn_create(ui_Screen5);
lv_obj_set_width( ui_ButtonBack2, 55);
lv_obj_set_height( ui_ButtonBack2, 35);
lv_obj_set_x( ui_ButtonBack2, 210 );
lv_obj_set_y( ui_ButtonBack2, 115 );
lv_obj_set_align( ui_ButtonBack2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonBack2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonBack2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonBack2, lv_color_hex(0x0D00FC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonBack2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Credit = lv_label_create(ui_Screen5);
lv_obj_set_width( ui_Credit, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Credit, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Credit, LV_ALIGN_CENTER );
lv_label_set_text(ui_Credit,"Credit: Tran Ngo Phuong Huy\nClass: 19DHDT02\nStudent ID: 1953020047\nVersion: 1.0 Beta\nDevice: ESP32-S3-WROOM-1U");

lv_obj_add_event_cb(ui_ButtonBack2, ui_event_ButtonBack2, LV_EVENT_ALL, NULL);

}
