// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1( lv_event_t * e);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Label4;
void ui_event_Button2( lv_event_t * e);
lv_obj_t *ui_Button2;
void ui_event_Button1( lv_event_t * e);
lv_obj_t *ui_Button1;
void ui_event_Button3( lv_event_t * e);
lv_obj_t *ui_Button3;
void ui_event_Button4( lv_event_t * e);
lv_obj_t *ui_Button4;
lv_obj_t *ui_Label5;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t *ui_Screen2;
void ui_event_Button5( lv_event_t * e);
lv_obj_t *ui_Button5;
void ui_event_Checkbox1( lv_event_t * e);
lv_obj_t *ui_Checkbox1;
void ui_event_Slider1( lv_event_t * e);
lv_obj_t *ui_Slider1;
void ui_event_Slider2( lv_event_t * e);
lv_obj_t *ui_Slider2;
void ui_event_Slider3( lv_event_t * e);
lv_obj_t *ui_Slider3;
void ui_event_Slider4( lv_event_t * e);
lv_obj_t *ui_Slider4;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Label7;
lv_obj_t *ui_Label8;
lv_obj_t *ui_Label9;
void ui_event_Switch1( lv_event_t * e);
lv_obj_t *ui_Switch1;
void ui_event_Switch2( lv_event_t * e);
lv_obj_t *ui_Switch2;
void ui_event_Switch3( lv_event_t * e);
lv_obj_t *ui_Switch3;
void ui_event_Switch4( lv_event_t * e);
lv_obj_t *ui_Switch4;
lv_obj_t *ui_Button9;
lv_obj_t *ui_Button10;
lv_obj_t *ui_Button11;
lv_obj_t *ui_Button12;
lv_obj_t *ui_Label12;
lv_obj_t *ui_Label13;
lv_obj_t *ui_Label14;
lv_obj_t *ui_Label15;


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t *ui_Screen3;
void ui_event_Button6( lv_event_t * e);
lv_obj_t *ui_Button6;
void ui_event_Arc2( lv_event_t * e);
lv_obj_t *ui_Arc2;
void ui_event_Button13( lv_event_t * e);
lv_obj_t *ui_Button13;
void ui_event_Button14( lv_event_t * e);
lv_obj_t *ui_Button14;
void ui_event_Button15( lv_event_t * e);
lv_obj_t *ui_Button15;
void ui_event_Button16( lv_event_t * e);
lv_obj_t *ui_Button16;
lv_obj_t *ui_Label10;


// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t *ui_Screen4;
void ui_event_Button7( lv_event_t * e);
lv_obj_t *ui_Button7;


// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
lv_obj_t *ui_Screen5;
void ui_event_Button8( lv_event_t * e);
lv_obj_t *ui_Button8;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen4_screen_init);
      _ui_screen_delete( &ui_Screen1);
}
}
void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
      _ui_screen_delete( &ui_Screen1);
}
}
void ui_event_Button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen5_screen_init);
      _ui_screen_delete( &ui_Screen1);
}
}
void ui_event_Button3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
      _ui_screen_delete( &ui_Screen1);
}
}
void ui_event_Button4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen4_screen_init);
      _ui_screen_delete( &ui_Screen1);
}
}
void ui_event_Button5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
      _ui_screen_delete( &ui_Screen2);
}
}
void ui_event_Checkbox1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_Switch1, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_Switch2, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_Switch3, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_Switch4, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_Slider1, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_Slider2, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_Slider3, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_Slider4, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_Switch1, LV_STATE_DISABLED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_Switch2, LV_STATE_DISABLED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_Switch3, LV_STATE_DISABLED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_Switch4, LV_STATE_DISABLED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_Slider1, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_Slider2, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_Slider3, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_Slider4, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
}
}
void ui_event_Slider1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_Label12, target, "", "");
}
}
void ui_event_Slider2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_Label13, target, "", "");
}
}
void ui_event_Slider3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_Label15, target, "", "");
}
}
void ui_event_Slider4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_Label14, target, "", "");
}
}
void ui_event_Switch1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_Button9, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_Button9, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
}
}
void ui_event_Switch2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_Button12, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_Button12, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
}
}
void ui_event_Switch3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_Button11, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_Button11, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
}
}
void ui_event_Switch4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_Button10, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      _ui_state_modify( ui_Button10, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
}
}
void ui_event_Button6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
      _ui_screen_delete( &ui_Screen3);
}
}
void ui_event_Arc2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( ui_Label10, target, "", "");
}
}
void ui_event_Button13( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      moveForward( e );
}
}
void ui_event_Button14( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      moveLeft( e );
}
}
void ui_event_Button15( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      moveRight( e );
}
}
void ui_event_Button16( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      moveBackward( e );
}
}
void ui_event_Button7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
      _ui_screen_delete( &ui_Screen4);
}
}
void ui_event_Button8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
      _ui_screen_delete( &ui_Screen5);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui_Screen2_screen_init();
ui_Screen3_screen_init();
ui_Screen4_screen_init();
ui_Screen5_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
